let toastTimer,playing=false,activeSheet='';
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600);}
function sheet(title,html,kind=''){if($('modal-layer').hidden)sheetReturnFocus=document.activeElement;$('sheet-title').textContent=title;$('sheet-body').innerHTML=html;$('modal-layer').hidden=false;$('app').inert=true;$('floating-bar').inert=true;activeSheet=kind;$('sheet-body').scrollTop=0;$('sheet').focus({preventScroll:true});if(document.body.classList.contains('full-page-mode'))$('sheet').scrollIntoView({block:'end',behavior:'instant'});}
function closeSheet(restore=true){if(!$('modal-layer'))return;$('modal-layer').hidden=true;$('app').inert=false;$('floating-bar').inert=false;activeSheet='';stopSpeech();if(restore&&sheetReturnFocus?.isConnected)sheetReturnFocus.focus({preventScroll:true});}
function menu(){sheet('更多',`<div class="sheet-menu">${actionButton(icon('plus')+'新建笔记'+icon('right'),'capture:notes')}${actionButton(icon('folder')+'管理文件夹'+icon('right'),'folders')}${actionButton(icon('collections')+'选择演示页面'+icon('right'),'scene-menu')}${actionButton(icon('note')+'演示说明'+icon('right'),'about')}${actionButton(icon('back')+'重置演示'+icon('right'),'reset')}</div>`);}
function sceneMenu(){sheet('演示页面',`<div class="sheet-menu">${Object.entries(PAGE_NAMES).map(([id,name])=>actionButton(esc(name)+icon('right'),'go:'+id)).join('')}</div>`);}
function showNote(id){const n=state.notes.find(n=>n.id===id);if(!n)return;sheet('笔记',`<h3>${esc(n.title)}</h3><div class="note-detail-meta">${icon('note')}${esc(n.date)} &nbsp;·&nbsp; ${esc(n.category||'随记')}</div><div class="note-body">${esc(n.text)}</div>${n.collection?actionButton('打开'+PAGE_NAMES[n.collection]+icon('right'),'go:'+n.collection,'secondary-button'):''}${actionButton('编辑笔记','edit-note:'+id,'secondary-button')}`,'note');}
function editNote(id){const n=state.notes.find(n=>n.id===id);if(!n)return;sheet('编辑笔记',`<form id="edit-note-form" data-id="${esc(id)}"><label for="edit-title">标题</label><input id="edit-title" value="${esc(n.title)}" required maxlength="80"><label for="edit-content">内容</label><textarea id="edit-content" required>${esc(n.text)}</textarea><button class="primary-button" type="submit">保存修改</button></form>`);}
function showSource(id){const s=sources[id];if(!s)return;sheet('原始记录',`<h3>${s.title}</h3><p class="meta">${s.date}${s.time?' · 录音转写':''}</p><div class="source-excerpt">${s.quote}</div>${s.time?`<p class="source-notice">示例转写 · ${s.time}｜当前演示未附原始音频</p>`:''}<div class="note-body">${s.body}</div>${actionButton('返回'+PAGE_NAMES[s.scope],'close','secondary-button')}`,'source');}
function sourceList(scope){if(scope==='cards'){sheet('卡证原始记录',credentials.map(c=>`<button class="source-list-row" data-action="credential-source:${c.id}">${icon('note')}<span>${c.title}<small>结构化卡证 · 示例记录</small></span>${icon('right')}</button>`).join(''));return;}const ids=Object.keys(sources).filter(id=>sources[id].scope===scope),supplements=state.supplements[scope]||[];sheet(PAGE_NAMES[scope]+' · 原始记录',`${supplements.map(id=>{const n=state.notes.find(n=>n.id===id);return n?`<button class="source-list-row" data-action="note:${id}">${icon('note')}<span>${esc(n.title)}<small>刚刚 · 补充记录</small></span>${icon('right')}</button>`:'';}).join('')}${ids.map(id=>`<button class="source-list-row" data-action="source:${id}">${icon('note')}<span>${sources[id].title}<small>${sources[id].date}${sources[id].time?' · 录音转写':''}</small></span>${icon('right')}</button>`).join('')}${actionButton(icon('plus')+' 补充记录','capture:'+scope,'secondary-button')}`);}
function collectionList(scope){const lists={ideas:[['和父母的相处','other:family'],['Agentic OS 的笔记','other:product'],['职业方向思考','go:ideas']],course:[['高等数学','go:course'],['大学物理','other:physics'],['化学','other:chemistry']],interview:[['笔记用户访谈','other:notes-interview'],['小米创作用户访谈','other:drawing'],['扫地机用户访谈','go:interview']],other:[['旅行计划','other:travel']]};sheet({ideas:'想法',course:'课程',interview:'访谈',other:'其他'}[scope],`<div class="sheet-menu">${lists[scope].map(([name,a])=>actionButton(name+icon('right'),a)).join('')}</div>`);}
function otherCollection(id){const info={family:['和父母的相处','关于家人 · 6 篇笔记','我妈今天问我什么时候回家，我说下个月，她就没再说话了。','反复出现的想法','你在意陪伴，也常常被工作占满时间。可以先把下次回家的具体日期定下来。'],product:['Agentic OS 的笔记','关于产品 · 5 篇笔记','当记录变得越来越容易，我们该怎样重新使用这些内容？','正在形成的思路','从单篇笔记走向合集，让资料变成知识、洞察和行动。来源始终可以追溯。'],physics:['大学物理','2026秋季学期 · 6 篇笔记','从运动与力开始，理解物体为什么会改变运动状态。','章节与知识点','质点运动学；牛顿运动定律；功与能；动量与碰撞。'],chemistry:['化学','2026秋季学期 · 6 篇笔记','从物质结构出发，认识化学键和化学反应。','章节与知识点','原子结构；化学键；化学平衡；酸碱与氧化还原。'],'notes-interview':['笔记用户访谈','记录与查找 · 6 篇笔记','记下来很容易，但过段时间就找不到了。','关键洞察','输入越来越方便，回看却需要整理。按场景组织相关内容，可以给用户更清晰的回顾入口。'],drawing:['小米创作用户访谈','数字绘画 · 5 篇笔记','要发挥平板的创作能力，还需要更顺手的工具。','关键洞察','从灵感草稿到完成作品，创作者需要连续的工作空间和熟悉的操作。'],travel:['旅行计划','南京两日 · 3 篇笔记','春日踏青，给周末留一点自由。','行程安排','第一天：南京博物院、明城墙、夫子庙。第二天：玄武湖、老门东。']};const d=info[id];if(!d)return;sheet('合集',`<h3>${d[0]}</h3><p class="meta">${d[1]}</p><div class="source-excerpt">${d[2]}</div><h4>${d[3]}</h4><p>${d[4]}</p>${id==='travel'?actionButton('查看南京旅行笔记','note:nanjing','secondary-button'):''}${['physics','chemistry'].includes(id)?actionButton('体验高等数学完整复习','go:course','secondary-button'):''}${actionButton('返回合集','close','secondary-button')}`);}
function findTask(id){for(const t of state.tasks){if(t.id===id)return {task:t,parent:null};const child=t.children?.find(c=>c.id===id);if(child)return {task:child,parent:t};}return null;}
function toggleTask(id){const match=findTask(id);if(!match)return;const t=match.task;t.done=!t.done;if(t.children)t.children.forEach(c=>c.done=t.done);if(match.parent)match.parent.done=match.parent.children.every(c=>c.done);persist();render();toast(t.done?'已完成':'已恢复为待办');}
function taskDetail(id){const match=findTask(id);if(!match)return;const t=match.task;sheet('待办详情',`<form id="task-edit-form" data-id="${esc(id)}"><label for="task-title">事项</label><input id="task-title" value="${esc(t.title)}" required maxlength="100"><label for="task-due">提醒时间</label><input id="task-due" value="${esc(t.time||'')}" placeholder="例如：明天 09:00"><label for="task-category">分类</label><select id="task-category">${['生活','新品发布会','装修','孩子','职业规划'].map(x=>`<option ${x===(t.category||match.parent?.category)?'selected':''}>${x}</option>`).join('')}</select><button class="primary-button" type="submit">保存</button></form>${actionButton(t.done?'恢复为待办':'标为已完成','task-sheet-toggle:'+id,'secondary-button')}${t.source==='ideas'?sourceLink('transfer'):''}`);}
function newTask(){sheet('新建待办',`<form id="task-create-form"><label for="task-title">要做什么</label><input id="task-title" placeholder="记下要做的事" required maxlength="100"><label for="task-due">提醒时间</label><input id="task-due" placeholder="例如：明天 09:00"><label for="task-category">分类</label><select id="task-category">${['生活','新品发布会','装修','孩子','职业规划'].map(x=>`<option ${x===taskFilter?'selected':''}>${x}</option>`).join('')}</select><button class="primary-button" type="submit">添加待办</button></form>`);}
function addIdeaAction(i){if(state.addedActions.includes(i))return false;state.tasks.unshift({id:'idea-action-'+i,title:ideaActions[i],time:'',category:'职业规划',source:'ideas',done:false});state.addedActions.push(i);return true;}
function addActions(index){if(index===undefined&&state.addedActions.length===3){taskFilter='全部';go('tasks');return;}let count=0;(index===undefined?[0,1,2]:[index]).forEach(i=>{if(addIdeaAction(i))count++;});persist();render();toast(count?`已添加 ${count} 项到待办`:'这项建议已在待办中');}
function addNote(title,text,scope='notes'){const id='new-'+state.nextId++;state.notes.unshift({id,title,text,date:'刚刚',category:['course','ideas','interview'].includes(scope)?'工作':'生活',collection:PAGE_NAMES[scope]&&scope!=='notes'&&scope!=='home'?scope:undefined});return id;}
function capture(scope,mode='text',keep=false){if(!keep){captureDraft='';captureScope=scope;captureMode=mode;}else captureMode=mode;const label=['course','ideas','interview'].includes(captureScope)?'补充到'+PAGE_NAMES[captureScope]:'新建笔记';sheet(label,`<div class="capture-modes">${[['text','文字'],['voice','语音'],['assistant','AI 助手']].map(([m,t])=>actionButton(t,'capture-mode:'+m,m===captureMode?'active':'')).join('')}</div>${captureMode==='voice'?`<div class="capture-recording"><div class="record-dot">${icon('mic')}</div><p>用一段示例语音体验快速记录</p></div>${actionButton('填入语音转写示例','voice-example','secondary-button')}`:captureMode==='assistant'?'<p class="source-notice">模拟 AI 助手写入笔记。可编辑以下内容后保存。</p>':''}<form id="capture-form"><label for="capture-text">${captureMode==='voice'?'转写内容':'记录内容'}</label><textarea id="capture-text" placeholder="此刻想到什么，记在这里…" required>${esc(captureDraft)}</textarea><button class="primary-button" type="submit">${captureScope==='notes'?'保存笔记':'保存到合集'}</button></form>`,'capture');}
function saveSummary(scope){const id='summary-'+scope;if(state.savedSummaries.includes(scope)){showNote(id);return;}const title=scope==='ideas'?'关于职业方向的思考':'扫地机器人购买决策';const text=scope==='ideas'?`${ideaSummary}\n\n方向上，转产品的意愿在逐渐清晰。\n${ideaDirection}\n\n给自己的下一步\n${ideaActions.join('\n')}`:`访谈目标\n${interviewGoal}\n\n核心结论\n${interviewConclusion}\n\n关键发现\n${interviewInsights.map(x=>x.title+'\n'+x.text).join('\n\n')}`;state.notes.unshift({id,title,text,date:'刚刚',category:'工作',collection:scope});state.savedSummaries.push(scope);persist();render();toast('已另存为笔记');}
function chooseChapters(){sheet('切换章节',chapters.map((c,i)=>`<button class="chapter-option ${i===chapterIndex?'active':''}" data-action="choose-chapter:${i}"><span class="chapter-number">0${i+1}</span><span>${c.title}<small>${c.total} 个知识点</small></span></button>`).join(''));}
const knowledgeContent=[
 [['把“靠近”说清楚','任意给定一个误差范围 ε，都能找到足够小的 δ，使 x 靠近 a 时，f(x) 落在 L 附近。','0 &lt; |x − a| &lt; δ<br>⇒ |f(x) − L| &lt; ε','函数在 a 点的值不决定极限是否存在。'],['从两侧夹住同一个值','若 g(x) ≤ f(x) ≤ h(x)，并且 g(x)、h(x) 都趋向 L，那么 f(x) 也趋向 L。','g(x) ≤ f(x) ≤ h(x)','先找到上下界，再证明上下界具有相同极限。'],['单调加有界，保证收敛','一个单调递增且有上界的数列收敛；单调递减且有下界同理。','单调 + 有界 ⇒ 收敛','两个条件都要核对，单调本身不保证收敛。'],['连续需要三个条件','函数在该点有定义；该点的极限存在；极限等于函数值。','lim f(x) = f(a)<br>x → a','极限存在不等于连续，还要检查函数值。']],
 [['变化率，也是切线斜率','导数是平均变化率在区间缩小时的极限。它描述函数在某点附近变化的快慢。',"f′(x) = lim [f(x+h)−f(x)] / h",'可导一定连续，连续不一定可导。'],['复合函数，一层一层求导','先求外层导数，再乘以内层导数。不要漏掉内层的变化率。',"(f(g(x)))′ = f′(g(x)) · g′(x)",'sin(x²) 的导数是 2x cos(x²)。'],['把 y 也看成 x 的函数','对等式两边同时求导，遇到 y 的项，要用链式法则带上 y′。',"x² + y² = 1 ⇒ y′ = −x/y",'上述表达式适用于 y ≠ 0 的位置。'],['先检查是否为未定式','满足适用条件时，可通过分子分母分别求导来计算 0/0 或 ∞/∞ 型极限。',"lim f(x)/g(x) = lim f′(x)/g′(x)",'使用之前要核对可导性、分母导数等条件。']],
 [['局部变化连接整体变化','闭区间连续、开区间可导时，至少存在一点的导数等于区间上的平均变化率。',"f′(ξ) = [f(b)−f(a)]/(b−a)",'罗尔定理对应端点函数值相等的情况。'],['比较两个函数的变化','柯西中值定理把两个函数的总体变化量与某点导数联系起来。',"[f(b)−f(a)]g′(ξ) = [g(b)−g(a)]f′(ξ)",'先确认两个函数都满足连续和可导条件。'],['看导数符号的变化','导数由正变负，对应局部极大；由负变正，对应局部极小。',"f′ > 0：递增 · f′ < 0：递减",'驻点不一定是极值点，还需检查邻域变化。'],['端点和关键点一起比较','闭区间上的最值，要比较端点、驻点和不可导点的函数值。','候选点 → 计算值 → 比较','不能只求导数为零的位置。']]
];
function study(key){const [ci,pi]=key.split('-').map(Number),d=knowledgeContent[ci]?.[pi];if(!d)return;sheet(chapters[ci].short[pi],`<h3>${d[0]}</h3><p>${d[1]}</p><div class="study-definition"><strong>${d[2]}</strong></div><p>${d[3]}</p>${sourceLink('course'+ci)}${actionButton(state.mastered.includes(key)?'已掌握 · 继续下一个':'我已掌握','master:'+key)}${actionButton('看看知识脉络','map:'+ci,'secondary-button')}`,'study');}
function markMastered(key){if(!state.mastered.includes(key))state.mastered.push(key);persist();render();const [ci,pi]=key.split('-').map(Number);if(pi<3){study(ci+'-'+(pi+1));toast('已更新学习进度');}else{closeSheet();toast('本组知识点已复习完成');}}
function knowledgeMap(ci){sheet('知识脉络',`<div class="map-tree"><div class="map-root">${chapters[ci].title}</div><div class="map-branch">${chapters[ci].short.map((x,i)=>actionButton(x+icon('right'),'study:'+ci+'-'+i,'map-leaf')).join('')}</div></div>`);}
const quizzes=[
 [{q:'函数在 a 点的极限存在，需要满足什么？',a:['函数在 a 点有定义','左右极限都存在且相等','函数在 a 点可导'],correct:1,why:'左右极限都存在且相等，极限才存在。函数在该点是否有定义，是另一个问题。'}, {q:'哪组条件可以保证数列收敛？',a:['单调且有界','单调递增','每一项都大于零'],correct:0,why:'单调有界数列必收敛，两个条件缺一不可。'}, {q:'极限存在且等于该点的函数值，说明函数在该点怎样？',a:['一定可导','一定有极值','连续'],correct:2,why:'连续要求该点有定义、极限存在且与函数值相等。'}],
 [{q:'sin(x²) 的导数是什么？',a:['cos(x²)','2x cos(x²)','2x sin(x²)'],correct:1,why:'链式法则：外层 sin 求导得到 cos，再乘以内层 x² 的导数 2x。'}, {q:'函数在一点可导，可以推出什么？',a:['在该点连续','在该点有极值','导数等于零'],correct:0,why:'可导必连续，但连续不一定可导。'}, {q:'对 x²+y²=1 作隐函数求导，在 y≠0 处 y′ 等于什么？',a:['x/y','−y/x','−x/y'],correct:2,why:'两边求导得到 2x+2y·y′=0，因此 y′=−x/y。'}],
 [{q:'拉格朗日中值定理要求函数满足什么？',a:['只在端点连续','闭区间连续，开区间可导','函数值始终为正'],correct:1,why:'连续与可导的范围都需要满足，才能使用中值定理。'}, {q:'导数在一点附近由正变负，通常对应什么？',a:['局部极大值','局部极小值','没有极值'],correct:0,why:'函数先增后减，因此在该点取得局部极大值。'}, {q:'求闭区间上的最值，需要比较哪些位置？',a:['只比较驻点','只比较端点','端点、驻点和不可导点'],correct:2,why:'要覆盖所有可能取得最值的位置，不能遗漏端点与不可导点。'}]
];
function quiz(i,answer=null){quizIndex=i;quizAnswer=answer;const q=quizzes[chapterIndex][i];sheet('考题自测 · '+(i+1)+'/3',`<p class="meta">第${chapterIndex+1}章 · ${chapters[chapterIndex].title}</p><h3>${q.q}</h3>${q.a.map((a,j)=>actionButton(`<span class="answer-letter">${'ABC'[j]}</span>${a}`,'quiz-answer:'+j,'quiz-answer '+(answer!==null?(j===q.correct?'correct':j===answer?'wrong':''):''),answer!==null?'disabled':'')).join('')}${answer!==null?`<div class="quiz-feedback"><b>${answer===q.correct?'答对了':'再看看这个知识点'}</b><br>${q.why}</div>${actionButton(i<2?'下一题':'完成自测',i<2?'quiz:'+(i+1):'quiz-finish')}`:''}`,'quiz');}
function slides(i){slideIndex=i;const deck=knowledgeContent[chapterIndex];const d=deck[i];sheet('复习课件 · '+(i+1)+'/4',`<div class="slide-card"><small>第 ${chapterIndex+1} 章 · ${chapters[chapterIndex].title}</small><h3>${d[0]}</h3><p>${d[1]}</p><p><b>${d[2]}</b></p></div><div class="slide-dots">${deck.map((_,j)=>`<i class="${i===j?'active':''}"></i>`).join('')}</div><div class="button-row">${actionButton('上一页','slides:'+(i-1),'secondary-button',i===0?'disabled':'')}${actionButton(i<3?'下一页':'完成复习',i<3?'slides:'+(i+1):'close','primary-button')}</div>${sourceLink('course'+chapterIndex)}`,'slides');}
function podcast(){sheet('播客精讲',`<div class="podcast-art">${icon('headphones')}<strong>${chapters[chapterIndex].title}</strong><div class="audio-bars" id="audio-bars">${'<i></i>'.repeat(22)}</div></div><p class="meta">用几分钟，听一遍这一章的重点</p><p id="podcast-script">${chapters[chapterIndex].summary} ${knowledgeContent[chapterIndex].map(x=>x[1]+x[3]).join(' ')}</p>${actionButton(icon('play')+' 播放精讲','podcast-play','primary-button','id="podcast-play-button"')}${actionButton('停止播放','podcast-stop','secondary-button')}<p class="source-notice">演示使用设备朗读预设脚本，未连接播客生成服务。</p>${sourceLink('course'+chapterIndex)}`,'podcast');}
function stopSpeech(){if(playing)window.speechSynthesis?.cancel();playing=false;$('audio-bars')?.classList.remove('playing');if($('podcast-play-button'))$('podcast-play-button').innerHTML=icon('play')+' 播放精讲';}
function playPodcast(){if(!('speechSynthesis' in window)){toast('设备暂不支持朗读，可以查看文字脚本');return;}if(playing){stopSpeech();return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('podcast-script').textContent);u.lang='zh-CN';u.rate=.93;u.onend=()=>stopSpeech();u.onerror=()=>{stopSpeech();toast('朗读暂不可用，请查看文字脚本');};playing=true;$('audio-bars').classList.add('playing');$('podcast-play-button').innerHTML=icon('pause')+' 停止朗读';window.speechSynthesis.speak(u);}
function chat(scope){chatScope=scope;chatLog=[];renderChat();}
function renderChat(){const intro={ideas:'我带上了这 6 条职业思考。可以一起梳理转产品的方向，或把下一步变得更具体。',course:'我带上了高等数学的课程记录。想换个方式理解知识点，还是一起做一道题？',interview:'我带上了这 3 位受访者的记录。可以继续比较人群差异，或追溯一个洞察的依据。'};const suggest={ideas:['我下一步可以做什么？','转产品的想法来自哪些记录？'],course:['用简单的话解释极限','我该先复习什么？'],interview:['比较三类用户的差异','这些结论的依据是什么？']};sheet('问问AI',`<div class="chat-context">${aiIcon()}${PAGE_NAMES[chatScope]} · 已带上合集内容</div><p class="source-notice">演示对话 · 使用预设回答</p><div id="chat-messages"><div class="chat-message">${intro[chatScope]}</div>${chatLog.map((m,i)=>`<div class="chat-message ${m.role==='user'?'user':''}">${esc(m.text)}</div>${m.role==='assistant'?actionButton(m.saved?'已保存为笔记':'另存为笔记','chat-save:'+i,'chat-save'):''}`).join('')}</div>${chatLog.length===0?`<div>${suggest[chatScope].map(x=>actionButton(x,'chat-suggestion:'+x,'chat-suggestion')).join('')}</div>`:''}<form class="chat-form" id="chat-form"><input id="chat-input" aria-label="提问" placeholder="继续问问…" autocomplete="off" required><button type="submit" aria-label="发送">${icon('send')}</button></form>`,'chat');if(chatLog.length)$('sheet-body').scrollTop=$('sheet-body').scrollHeight;}
function sendChat(text){const q=text.trim();if(!q)return;const replies={ideas:/来源|记录|依据/.test(q)?'这条方向主要来自两条记录：\n\n「关于产品方向」里，你说想了解需求背后是怎么定的。\n「内部转岗」里，你说如果能转产品，在哪家公司反而没那么重要。\n\n可以回到原始记录，确认这些想法今天是否仍然成立。':'可以先做三件小事：\n1. 找一位产品同事，了解内部转岗的条件。\n2. 在下个需求中参与目标和范围的定义。\n3. 用一个月练习提前对齐技术边界。\n\n先验证自己是否喜欢产品工作的实际内容，再决定去留。',course:/复习|先|计划/.test(q)?'建议从当前章节的定义开始，接着看一条例子，再做一道自测。\n\n如果定义仍然模糊，先不要急着刷题。课程里的「继续学习」可以按知识点逐个回顾。':'极限是在问：当 x 越来越靠近某个位置时，函数值会越来越靠近什么？\n\n我们关心靠近过程中的趋势，而不一定关心最后那个点的函数值。左右两边要走向同一个数，极限才存在。',interview:/依据|原话|来源/.test(q)?'可以直接对照三条原话：\n陈曦：「我要的是彻底解放双手。」\n刘婷：「我怕它扫不干净还得我返工。」\n老周：「我就想按一个键它就开始扫。」\n\n这些差异支撑了人群需求分化的洞察；当前只有三个示例样本，仍需更多访谈验证。':'三类人群的优先级不同：\n\n陈曦：把日常维护一起自动化。\n刘婷：先证明清洁效果，减少返工。\n老周：让操作保持简单，一键就能开始。\n\n下一轮可以让三类用户试用同一个任务流程，再观察各自卡在哪一步。'};chatLog.push({role:'user',text:q},{role:'assistant',text:replies[chatScope],saved:false});renderChat();}
async function copyCredential(id){const c=credentials.find(c=>c.id===id);if(!c)return;try{await navigator.clipboard.writeText(c.value);toast('已复制示例'+c.secretLabel);}catch{sheet('复制'+c.secretLabel,`<p class="source-notice">当前浏览器未开放剪贴板权限，可长按下方内容手动复制。</p><input value="${esc(c.value)}" readonly aria-label="可复制的示例内容">`);$('sheet-body').querySelector('input').select();}}
function about(){sheet('演示说明','<h3>OS5 笔记</h3><p>根据你提供的 7 张原型重建。笔记、合集、课程、待办、想法、访谈和卡证页面可点击体验。</p><h4>可以体验什么</h4><p>搜索与筛选、勾选待办、展开洞察、查看来源、保存总结、补充记录、章节学习、自测和卡证复制。</p><h4>示例与保存</h4><p>这里使用示例数据。AI 对话、语音写入和系统提醒为模拟；播客使用设备朗读。卡证中的可显示号码与密码均为虚构演示值。</p><p>新增笔记、待办和学习状态仅保存在当前浏览器。没有写入真实笔记、系统日历或外部 AI 服务。</p><h4>对照原型</h4><p>桌面左侧可以打开原图对照，并切换完整页面。字体与图标会受设备环境影响。</p>');}
